name: Daily Repo Scrape

on:
  schedule:
    - cron: "20 15 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.17

      - name: Get runner public IP
        id: get_ip
        run: |
          IP=$(curl -s https://ipinfo.io/ip)
          echo "Runner public IP: $IP"
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Verify MongoDB connection (Node.js)
        run: >
          node -e "import('mongodb')
            .then(({MongoClient}) =>
              MongoClient.connect(process.env.MONGO)
                .then(c => c.close()))"
        env:
          MONGO: ${{ secrets.MONGO }}

      - name: Run scraper
        run: bun scheduler-batched.ts --run-batched
        env:
          MONGO: ${{ secrets.MONGO }}
          PORT: ${{ secrets.PORT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
