name: Daily Repo Scrape

on:
  schedule:
    - cron: "20 15 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get runner public IP
        id: get_ip
        run: |
          IP=$(curl -s https://ipinfo.io/ip)
          echo "Runner public IP: $IP"
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: npm install

      - name: Build scraper
        run: npm run build:scraper

      - name: Run scraper
        run: npm run scrape:batched
        env:
          MONGO: ${{ secrets.MONGO }}
          PORT: ${{ secrets.PORT }}
          GITHUB_TOKEN: ${{ github.token }}
          ATLAS_PRIVATE_KEY: ${{ secrets.ATLAS_PRIVATE_KEY }}
          ATLAS_PUBLIC_KEY: ${{ secrets.ATLAS_PUBLIC_KEY }}
          ATLAS_PROJECT_ID: ${{ secrets.ATLAS_PROJECT_ID }}
